# Generated by Django 4.1.6 on 2023-02-03 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comentario',
            name='email_comentario',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='comentario',
            name='nome_comentario',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='comentario',
            name='post_comentario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicado_comentario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario_comentario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
